# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    session:
        handler_id: null
        storage_factory_id: session.storage.factory.native
        save_path: '/tmp/sessions'
        cookie_secure: auto
        cookie_samesite: lax
    csrf_protection:
        enabled: true
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

    #esi: true
    #fragments: true

when@test:
    framework:
        session:
            handler_id: null
            storage_factory_id: session.storage.factory.mock_file
            cookie_secure: auto
            cookie_samesite: lax
        csrf_protection:
            enabled: true
        test: true

        assets:
            json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'